### PR TITLE
add heartbeat response (#9)

### PR DESCRIPTION
**Pull request by tdihp**
Hi, I added heartbeat, so that storm 0.9.3 may work.

### CODE REVIEW

**Comment by jswetzen** [comment]
This failed when I tried it, the ack after a heartbeat sync makes Storm throw an error. Also, because _process_tuple is overridden in SimpleBolt, the heartbeat code will be needed in both of the classes. I don't want to "steal" the commit, but I have a version that works: jswetzen/pyleus@a929e425cd86d6f9cca87c6b5d37664184f19d99

**Comment by poros** [comment]
I am up for merging the change as in @jswetzen commit and do not block this on #82. It seems to get the job done and a bit of code replication won't hurt that much if we know we are going to change it in the future.

@jswetzen: in order not to steal @tdihp you can `git rebase` your work on his branch (or `git cherry-pick` his commit or stuff like that); otherwise you can just open a new pull request. Whatever works for the two of you is good, guys.

**Comment by tdihp** [comment]
@poros, @jswetzen: I'm okay without commit log.

**Comment by poros** [comment]
Moved to #97

**Pull request closed without merging**
