### PR TITLE
Added trusted host argument to pip when running local pypi server

### LINKED ISSUE #133: development env broken
when using the dev config as stated in document:

```
[build]
pypi_index_url: http://0.0.0.0:7778/simple/
```

I could not get rid of the error message:

```
New python executable in /var/folders/g6/75g37v6x3yz5gk91f_kxggs00000gn/T/tmp6Cyj4S/resources/pyleus_venv/bin/python
Installing setuptools, pip, wheel...done.
Collecting pyleus==0.3.0
  The repository located at 0.0.0.0 is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host 0.0.0.0'.
  Could not find a version that satisfies the requirement pyleus==0.3.0 (from versions: )
No matching distribution found for pyleus==0.3.0
pyleus build: error: [VirtualenvError] Failed to install pyleus==0.3.0 package. Run with --verbose for detailed info.
```

when run `pyleus build ...yaml` the `pip install` would fail with the local pypi server.

I even tried to add `--trusted-host` to `build.py` and reinstall pyleus from source, but it is still a no go.

Please help to clarify how should I set up a dev environment.

I am going to open a pull request for adding some more config to topology, I really need a dev environment up and running ...

### PR DESCRIPTION
**Pull request by mzbyszynski**
Fixes #133

### CODE REVIEW

**Comment by mzbyszynski** [comment]
Oops, looks like I broke a unit test. I'll fix that shortly.

**Comment by imcom** [comment]
this patch is essential for building and testing pyleus on development stage

**Comment by poros** [comment]
+1
That's a very good point!
I use an older version of pip, so I never noticed it.

**Comment by poros** [comment]
Giving a second thought to it, it should possible to specify the same option in your `pip.conf` file and get away with it, without forcing pylues to do that for you.

I do not have a strong preference, but I am wondering if this change might break for old pip versions.

**Comment by mzbyszynski** [comment]
I think older versions pip just ignore the argument, but I'll try and confirm tonight or tomorrow.

**Comment by mzbyszynski** [comment]
Actually @poros you are right about the older versions of pip.. they barf on that argument. I think your `pip.conf` idea is a good solution. Maybe there just needs to be some note on the _contributing_ page of the documentation that describes how to do this if you are using pip 7 or whatever version added the new `trusted-host` parameter?

**Comment by poros** [comment]
Thank you for trying that out. Yes, a tip in the documentation is the best solution. Do you want to change this PR to do that so you get at least one commit with your name on it? Otherwise I'll do that as soon as I have some spare time.

**Comment by mzbyszynski** [comment]
No need to wait for me. If I manage to get the pip.conf to work in my environment I'll write something up, if you don't get to it first.

Thanks!

**Pull request closed without merging**
